version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget gcc clang libssl-dev rsync flex bison cpio libncurses5 curl python-is-python3
           git config --global user.name "prorooter007"
           git config --global user.email "shreyashwasnik112@gmail.com"
           git config --global color.ui false
           git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
           mkdir predator
           cd predator
           wget https://raw.githubusercontent.com/prorooter007/android_kernel_samsung_exynos2100/main/build_menu
           source build_menu
   parallelism: 4
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
